---
name: sonicverse-liquidsoap
services:
  liquidsoap:
    image: ghcr.io/sonicverse-eu/liquidsoap-audiostack:latest
    container_name: liquidsoap
    volumes:
      - ./scripts:/scripts
      - ./audio:/audio
      - ./silence_detection.txt:/silence_detection.txt
    environment:
      - TZ=Europe/Amsterdam
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
    env_file:
      - .env
    ports:
      - '0.0.0.0:8888:8888/tcp'
      - '0.0.0.0:9999:9999/tcp'
    command: /scripts/radio.liq
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    environment:
      - ICECAST_HOSTNAME=${ICECAST_HOSTNAME}
    restart: unless-stopped
    user: "liquidsoap:liquidsoap"

  icecast:
    image: ghcr.io/libretime/icecast:debian
    container_name: icecast
    environment:
      - TZ=Europe/Amsterdam
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
      - ICECAST_RELAY_PASSWORD=${ICECAST_RELAY_PASSWORD}
      - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}
      - ICECAST_ADMIN_USERNAME=${ICECAST_ADMIN_USERNAME}
      - ICECAST_ADMIN_EMAIL=${ICECAST_ADMIN_EMAIL}
      - ICECAST_LOCATION=${ICECAST_LOCATION}
      - ICECAST_HOSTNAME=${ICECAST_HOSTNAME}
      - ICECAST_MAX_CLIENTS=${ICECAST_MAX_CLIENTS}
      - ICECAST_MAX_SOURCES=${ICECAST_MAX_SOURCES}
    env_file:
      - .env
    volumes:
      - ./icecast/config:/config
      - ./icecast/log:/config/log
    ports:
      - "8000:8000"
    restart: unless-stopped
