---
name: sonicverse-liquidsoap
services:
  liquidsoap:
    image: ghcr.io/sonicverse-eu/liquidsoap-audiostack:latest
    container_name: liquidsoap
    volumes:
      - ./scripts:/scripts
      - ./audio:/audio
      - ./silence_detection.txt:/silence_detection.txt
    environment:
      - TZ=Europe/Amsterdam
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
    env_file:
      - .env
    ports:
      - '0.0.0.0:8888:8888/udp' # SRT Input 1
      - '0.0.0.0:9999:9999/udp' # SRT Input 2
    command: /scripts/radio.liq
    restart: unless-stopped
    user: "liquidsoap:liquidsoap"

  icecast:
    image: linuxserver/icecast:latest
    container_name: icecast
    environment:
      - TZ=Europe/Amsterdam
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
    volumes:
      - ./icecast/config:/config
      - ./icecast/log:/config/log
    ports:
      - "8000:8000"
    restart: unless-stopped
